# Generated by Django 4.1 on 2022-11-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_autor_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="editora",
            name="site",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="livro",
            name="preco",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="livro",
            name="quantidade",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
