# Generated by Django 4.1 on 2022-09-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_autor_remove_editora_site_livro"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="autores",
            field=models.ManyToManyField(related_name="livros", to="core.autor"),
        ),
    ]
